# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-03 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160703_1357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
